### ISSUE TITLE
Consider return &mut T for read()

### ISSUE THREAD

**Issue by unrealhoang** [HadrienG2/triple-buffer#11]
Hi, thank you for this project.

The underlying `output_buffer()` is already `&mut T` https://github.com/HadrienG2/triple-buffer/blob/master/src/lib.rs#L332, it's easier for non-raw read API to use the buffer on consumption, also probably deprecate raw read API as well.

What do you think?

**Comment by HadrienG2** [comment]
The main reason why you need to opt into the raw read API with a cargo feature, as opposed to it being always available, is that if the reader is allowed to mutate its buffer the changes must be synchronized back with the writer to avoid racey calls to `Drop` on the writer's side.

This synchronization requires [stronger atomics memory ordering](https://github.com/HadrienG2/triple-buffer/blob/master/src/lib.rs#L399), which can have various harmful effects on performance:

- On every hardware architecture including x86, this reduces the compiler's ability to reorder and optimize out code (e.g. obviously the writer-side `Drop` code must reload the value from memory instead of being allowed to keep it cached in registers).
- On most CPU architectures besides x86 (ARM, POWER, RISC-V, ...), this also forces atomics to [be compiled into stronger synchronization code](https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html), which in turn can increase the microarchitectural impact of synchronization (e.g. less ability to optimize code surrounding the synchronization transaction with tricks like speculation).

Although [LLVM's code generation for atomics is currently so terrible](https://bugs.llvm.org/show_bug.cgi?id=37716) that the extra optimization potential is unlikely to be leveraged properly by rustc, I have hope that this will change in the future as their optimizer progresses, and would like to keep my atomics memory orderings minimal accordingly.

**Comment by HadrienG2** [comment]
FWIW, this is the "small performance cost" which the raw cargo feature documentation tries to allude to without drowning the reading in implementation details. Do you think I could state the problem more clearly without making the sentence too verbose/technical?

**Comment by unrealhoang** [comment]
I see, this is indeed a breaking change. I understand it now, thank you for your very detailed explanations.
