### ISSUE TITLE
Consider directly returning (Input, Output) from new()

### ISSUE THREAD

**Issue by HadrienG2** [HadrienG2/triple-buffer#8]
Although surprising, this avoids unnecessary TripleBuffer::new().split() chains, and I cannot think of a real future use case for the un-split TripleBuffer struct.

Some variant of the new() method should remain internally for testing purposes.

This is a breaking API change, so I won't do it until the next major release, whenever/if that happens.

**Comment by nyanpasu64** [comment]
Hi, I built a similar but internal/unpublished crate based around the same principle (as did [yet another person](https://github.com/Ralith/oddio/blob/main/src/swap.rs)) and just discovered this crate. I actually hit on the same issue myself, but with a slightly different motivation. I'm not sure if you're interested in unsolicited feedback, but I hope this is helpful.

An approach I considered was to return `SharedState` directly, and supply two different `split` methods, one which consumes `self` and returns a reader/writer each with an `Arc`, and another which takes `&mut self` and returns a reader/writer each with a `&self`.

Anyway my code is at https://github.com/nyanpasu64/spectro2/blob/generic-flip-cell/src/sync2.rs#L56. I didn't end up using that branch due to complexity and fears of users instantiating `FlipWriter<Ptr>` with a malicious `Ptr` type. But that can't happen because `FlipWriter`'s fields are private, so only this module can create instances of the type, with specifically chosen `Ptr`.

The `&self` variation will not require heap allocation. Unfortunately it's probably difficult to use safely, because you can't move non-`'static` references into `std` threads, requiring you to use scoped threads. If you need to send a `&self` to a thread whose lifetime isn't bounded to a function call, you'd have to use unsafe code (I'm not sure what).

The advantage is that it's likely `no_std` compatible and doesn't require `alloc` (whereas `Arc<T>` is `no_std` compatible only if you're using the partly-unstable `alloc` crate). However I've never used no_std, so I don't know if "triple buffering as a library" is useful in embedded systems, and if it's worth the code complexity.

**Comment by HadrienG2** [comment]
Sorry for taking a while to reply, I took some holidays from my mailbox and am still in the process of going through the accumulated notifications...

I conceptually like the idea of not forcing heap allocation onto the users, but I share your concern about whether the extra complexity is worthwhile. It would be nice to have someone with a concrete use case in mind, who would be willing to expose it a bit here. This would serve both as a motivation, and also as a set of constraints to fuel the API design process.

To give you an example of the latter, the easiest way to share data between threads/CPUs without dynamic memory allocation is actually to use global / static variables, and that's a fairly common way to handle lack of dynamic memory allocators in an embedded setting. But if people wanted to use a triple buffer that way, then an interface which is based on the `&'shared mut SharedState -> (Reader<'shared>, Writer<'shared>)` pattern would not be enough, as the Rust compiler doesn't guarantee that only one thread will acquire an `&mut` to the shared state (which is why static mut is unsafe in Rust).

Instead, to have a safe interface in that usage pattern, we would need something like this, for which we could provide an auto-generation macro:

```rust
// Notice that this isn't "pub", that is important in order to guarantee the safety invariants
static mut STATE: SharedState = /* ... */;  // NOTE: Assumes the SharedState constructor is a const fn,
                                            //       else we also need a dynamic initialization procedure.
static ACQUIRED: AtomicBool = AtomicBool::new(false);

pub fn acquire() -> Option<&'static mut SharedState> {
    if !ACQUIRED.swap(true, Ordering::Relaxed) {
        Some(unsafe { &mut STATE })
    } else {
        None
    }
}
```

This is obviously quite different from the scoped thread approach. And an approach based on fully unsafe APIs, where it's the user's job to ensure that the SharedState lives long enough, would once again look different (basically we would need to provide an unsafe constructor of `Reader<'static>` and `Writer<'static>` from `NonNull<SharedState>`, which would have as safety invariants that 1/the Reader and Writer must be dropped before the SharedState is dropped and 2/the caller shall not build multiple readers and writers for a single shared state).

**Comment by HadrienG2** [comment]
In any case, this does indeed justify keeping the `.split()` design for now, as it gives API design headroom for such future evolutions. So I guess I can close this issue once we've finished the above discussion.
